services:
  - type: web
    name: f1686s-browser
    runtime: node
    repo: https://github.com/tranquyetchienbank-ops/f1686s-browsr.git
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    region: singapore
